databases:
  - name: SpoHeal
    ipAllowList: []

services:
  - type: web
    name: SpoHeal
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SpoHeal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
  - type: worker
    name: sidekiq
    env: ruby
    startCommand: "bundle exec sidekiq"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SpoHeal
          property: connectionString