databases:
  - name: SpoHeal
    ipAllowList: []

services:
  - type: web
    name: SpoHeal
    env: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; rails db:seed;
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SpoHeal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: Starter
    maxmemoryPolicy: noeviction